### ISSUE TITLE
Criar Ata da Reunião 01/09/2023

### ISSUE THREAD

**Issue by joao-artl** [unb-mds/2023-2-Squad09#1]
# Criar Ata da reunião 01/09/2023

## Descrição do problema
Criar Ata abordando os assuntos tratados na reunião do dia 01/09

## Critérios de aceitação

- [x] Arquivo .md

**Comment by DudaV228** [comment]
A Ata foi adicionada e pode ser visualizada no seguinte: [Link](https://github.com/unb-mds/2023-2-Squad09-Gotinha/blob/main/docs/AtaReuniao/ataReuniao01-09.md)
