### ISSUE TITLE
Estudo sobre Metodologias Ágeis

### ISSUE THREAD

**Issue by joao-artl** [unb-mds/2023-2-Squad09#10]
# Estudo sobre Metodologias Ágeis

## Descrição do problema
Estudo sobre as principais metodologias ágeis(Scrum e Kanban) e sobre como podemos aplica-las durante o projeto

## Como o problema pode ser resolvido
Documentar através de uma arquivo em markdown os conhecimentos adquiridos, visando realizar um futuro treinamento para os demais membros da equipe

## Critérios de aceitação

- [x] Arquivo .md
- [x] Links úteis

**Comment by yanzin00** [comment]
Vídeo que mostra de forma clara e como é a utilização do Scrum e o motivo de usa-ló [https://www.youtube.com/watch?v=3aCww_1RnL0](url)

**Comment by yanzin00** [comment]
uma plataforma que usa o método Scrum [https://trello.com](url) e um tutorial para implementar o Scrum e o Trello [https://blog.trello.com/br/tutorial-scrum](url)

**Comment by yanzin00** [comment]
https://blog.trello.com/br/tutorial-scrum

**Comment by yanzin00** [comment]
Vídeo que mostra de forma clara, como é a utilização do Scrum e o motivo de usa-ló https://www.youtube.com/watch?v=3aCww_1RnL0

**Comment by yanzin00** [comment]
uma plataforma que usa o método Scrum https://trello.com e um tutorial para implementar o Scrum e o Trello https://blog.trello.com/br/tutorial-scrum

**Comment by yanzin00** [comment]
Documento contendo um resumo sobre o framework Scrum [https://github.com/unb-mds/2023-2-Squad09/blob/main/docs/Estudos/scrum.md](url)

**Comment by yanzin00** [comment]
Documento contendo um resumo sobre o framework Scrum: [Link](https://github.com/unb-mds/2023-2-Squad09-Gotinha/blob/main/docs/Estudos/scrum.md)

**Comment by DudaV228** [comment]
Resumo em Markdown sobre oq é kanban e como usar [O que é kanban](https://github.com/unb-mds/2023-2-Squad09-Gotinha/blob/main/docs/Estudos/Kanban.md)

**Comment by DudaV228** [comment]
Vídeo que fala da relação do Scrum com o Kanban [Scrum e Kanban](https://www.youtube.com/watch?v=XfvQWnRgxG0)
