### ISSUE TITLE
Estudo sobre os principais documentos de um projeto de Software

### ISSUE THREAD

**Issue by joao-artl** [unb-mds/2023-2-Squad09#12]
# Estudo sobre os principais documentos de um projeto de Software

## Descrição do problema
- Estudar sobre os principais documentos de software permite um melhor entendimento do processo de documentação de um projeto. 
- Essa issue visa capacitar através de um treinamento todos os membros do grupo sobre este assunto, para que assim seja possivel definir um escopo para o projeto.

## Como o problema pode ser resolvido
- Elaborando um arquivo .md contendo informações sobre os principais tipos de documentação (Documento de Visão, Documento de Arquitetura, Termo de Abertura do Projeto), além de criar um treinamento deste assunto para os demais membros da equipe.

## Critérios de aceitação

- [x] Documento de Visão
- [x] Documento de Arquitetura
- [x] TAP

**Comment by LuizGust4vo** [comment]
[Arquivo](https://github.com/unb-mds/2023-2-Squad09-Gotinha/blob/main/docs/Estudos/Documento_de_Arquitetura.md) contendo informações sobre Documentação de Arquitetura de Software.

**Comment by LuizGust4vo** [comment]
[Arquivo](https://github.com/unb-mds/2023-2-Squad09-Gotinha/blob/main/docs/Estudos/Documento_de_Vis%C3%A3o.md) contendo informações sobre Documentação de Visão de Software.

**Comment by joao-artl** [comment]
[Arquivo](https://github.com/unb-mds/2023-2-Squad09-Gotinha/blob/main/docs/Estudos/TAP.md) contendo informações sobre o Termo de Abertura do Projeto (TAP)
