### ISSUE TITLE
Estudar requisitos funcionais e não funcionais

### ISSUE THREAD

**Issue by joao-artl** [unb-mds/2023-2-Squad09#13]
# Estudar requisitos funcionais e não funcionais

## Descrição do problema
Os requisitos desempenham um papel fundamental no desenvolvimento de um projeto de software e têm uma importância significativa em todas as fases do ciclo de vida do desenvolvimento de software. Considerando isso é necessário deixar este conceito muito bem definido para todos os membros.

## Como o problema pode ser resolvido
- Realizar um estudo sobre a diferença entre requisitos funcionais e não funcionais,
- Documentar tudo
-  Disponibilizar links úteis para o entendimento dos conceitos
-  É necessário marcar um treinamento para os demais membros. 

## Critérios de aceitação

- [x] Arquivo contendo a documentação do estudo
- [x] Links úteis

**Comment by paulomh** [comment]
[Documentação do estudo](https://github.com/unb-mds/2023-2-Squad09-Gotinha/blob/main/docs/Estudos/requisitos.md)

**Comment by paulomh** [comment]
Todos os links úteis se encontram no arquivo contendo a documentação do estudo

**Comment by paulomh** [comment]
Treinamento marcado para a próxima reunião do dia 12/09/2023
