### ISSUE TITLE
Montar uma planilha para acompanhamento das horas de trabalho de cada membro da equipe

### ISSUE THREAD

**Issue by joao-artl** [unb-mds/2023-2-Squad09#15]
# Montar uma planilha para acompanhamento das horas de trabalho de cada membro da equipe

## Descrição do problema
Registrar as horas de trabalho de uma equipe é de suma importância, pois isso não apenas fornece um controle eficaz sobre a alocação de issues e o cumprimento de prazos, mas também permite uma gestão mais precisa do projeto. Além disso, o registro de horas proporciona uma base sólida para avaliar a produtividade da equipe, permite também identificar membros que podem precisar de auxílio nas tarefas e promove a equidade na distribuição de trabalho.

Todos esses pontos tornam a planilha uma peça fundamental no desenvolvimento do projeto

## Como o problema pode ser resolvido
Existem vários aplicativos que possibilitam registrar as horas de trabalho de uma equipe, como o Clockfy.

## Critérios de aceitação

- [x] Montar uma planilha em algum aplicativo que permita acompanhar as horas de trabalho de cada membro da equipe

**Comment by Mxrcio** [comment]
Optamos pelo uso do Clockify como nossa ferramenta para registrar as horas trabalhadas, pois ela é simples e atende às nossas necessidades. Permite que cada um de nós registre suas horas e tarefas de forma eficiente.

Aqui está o link para o breve vídeo que fiz, explicando sobre a ferramenta e como ela funciona.

(https://www.youtube.com/watch?v=iX8RSEhJenU)
