### ISSUE TITLE
Estudo sobre Python (Scrapy e Pandas)

### ISSUE THREAD

**Issue by joao-artl** [unb-mds/2023-2-Squad09#19]
# Estudo sobre Python (Scrapy e Pandas)

## Descrição do problema

A principal linguagem utilizada pelo Querido Diário é o Python, sendo o Scrapy e o Pandas as principais biliotecas utilizadas. Considerando isso é importante que haja um treinamento para que todos os membros saibam suas principais funções.

## Como o problema pode ser resolvido

- Estudar sobre a biliotecas através de tutoriais, documentação das biliotecas e fóruns.
- Documentar o que foi estudado.

## Critérios de aceitação

- [x] Documentar estudo
- [x] Links úteis
- [x] Exemplo de um tutorial

**Comment by paulomh** [comment]
Estudo sobre Pandas finalizado.
[Documentação](https://github.com/unb-mds/2023-2-Squad09-Gotinha/blob/main/docs/Estudos/Pandas.ipynb) contendo links úteis, todo o estudo feito até então e diversos exemplos.

**Comment by LuizGust4vo** [comment]
[Arquivo](https://github.com/unb-mds/2023-2-Squad09-Gotinha/blob/main/docs/Estudos/Scrapy1.md) contendo informações de instalação e funcionalidades do Scrapy pelo terminal.
