### ISSUE TITLE
Estudar sobre o GitHub

### ISSUE THREAD

**Issue by joao-artl** [unb-mds/2023-2-Squad09#2]
# Estudar sobre o GitHub

## Descrição do problema
Realizar o estudo sobre o Git e GitHub, para eventualmente realizar um treinamento com os demais membros do grupo.

## Critérios de aceitação
- [x] Documento ensinando a utilizar o GitHub
- [x] Informações complementares do Git
- [x] Links úteis

Obs: O arquivo realizado por esta Issues pode ser utilizado em conjunto com o arquivo [Comandos Git](https://github.com/unb-mds/2023-2-Squad09/blob/main/docs/Estudos/ComandosGit.md).

**Comment by LuizGust4vo** [comment]
[Arquivo](https://github.com/unb-mds/2023-2-Squad09-Gotinha/blob/main/docs/Estudos/Treinamento_GitHub.md) desenvolvido para auxiliar os membros dos grupos a utilizarem as ferramentas Git e GitHub, bem como para servir de material base para um futuro treinamento.
