### ISSUE TITLE
Estudar sobre API

### ISSUE THREAD

**Issue by joao-artl** [unb-mds/2023-2-Squad09#26]
# Estudar sobre API

## Descrição do problema

O querido diário possui uma API com todas as funções do projeto, antes de entender cada metódo é preciso que todos os membros saibam como funciona uma API.

## Como o problema pode ser resolvido

- Pesquisar sobre API através de videos, tutoriais e documentos. 
- Realizar um treinamento para os demais membros.

## Critérios de aceitação

- [x] Documentar estudo
- [x] Links úteis

**Comment by DudaV228** [comment]
Estudo sobre a API do projeto feita, ela será o querido diario: [Querido diário](https://queridodiario.ok.org.br/api/docs)

**Comment by DudaV228** [comment]
[Estudo](https://github.com/unb-mds/2023-2-Squad09-Gotinha/blob/main/docs/Estudos/API.md) sobre o que é API e a funcionalidade para o nosso projeto
