### ISSUE TITLE
Assistir aos vídeos de Python do Querido Diário

### ISSUE THREAD

**Issue by joao-artl** [unb-mds/2023-2-Squad09#28]
# Assistir aos vídeos de Python do Querido Diário

## Descrição do problema
O Querido Diário possui vídeos que explicam o funcionamento e como são feitos os raspadores do projeto, assistir esses vídeos é uma forma de melhorar o entendimento sobre o Querido Diário como um todo.

## Critérios de aceitação

- [x] Assistir os vídeos

**Comment by LuizGust4vo** [comment]
Todos os membros assistiram aos videos.
