### ISSUE TITLE
Estudo sobre o Exoonero

### ISSUE THREAD

**Issue by joao-artl** [unb-mds/2023-2-Squad09#30]
# Estudo sobre o Exoonero

## Descrição do problema
O Exoonero é um projeto responsável por mostrar o número de nomeações e exonerações de determinados múnicipios a partir dos seus diários oficiais. O modelo do projeto é similar ao funcionamento do Querido Diário.

## Como o problema pode ser resolvido
O exoonero possui um [repositório](https://github.com/exoonero/extrator) no GitHub contendo toda sua documentação.

## Critérios de aceitação

- [x] Documentar estudo
- [x] Apresentação para equipe

**Comment by yanzin00** [comment]
[Site do Exoonero](https://exoonero.org/sobre/)

**Comment by yanzin00** [comment]
[Site do Exoonero](https://exoonero.org)

**Comment by yanzin00** [comment]
Doc com estudo sobre o Exoonero [Linkzin](https://github.com/unb-mds/2023-2-Squad09-Gotinha/blob/main/docs/Estudos/Exoonero.md)
