### ISSUE TITLE
Criar um bot usando Selenium

### ISSUE THREAD

**Issue by joao-artl** [unb-mds/2023-2-Squad09#32]
# Criar um bot usando Selenium

## Descrição do problema
O Selenium é uma biblioteca capaz de acessar sites de forma automática, podendo ser utilizado para obter informações especificas em algum site, como o Diário Oficial de alguma cidade específica. 

## Como o problema pode ser resolvido
Criar um algoritmo capaz de acessar um site e preencher as informações exigidas nele. Exemplo: Login no SIGAA

## Critérios de aceitação

- [x] Algoritmo funcional
- [x] Documentar funcionamento

**Comment by paulomh** [comment]
Algoritmo funcional utilizando selenium python: [BotSelenium](https://github.com/unb-mds/2023-2-Squad09-Gotinha/blob/main/Prot%C3%B3tipos/Prot%C3%B3tipoSelenium/botselenium.py)
