### ISSUE TITLE
Criar um Raspador usando Scrapy

### ISSUE THREAD

**Issue by joao-artl** [unb-mds/2023-2-Squad09#33]
# Criar um Raspador usando Scrapy

## Descrição do problema
Uma vez que o estudo sobre o Scrapy foi realizado, é importante que seja implementado um exemplo de uso da biblioteca.

## Como o problema pode ser resolvido
Criar um raspador utilizando a bilioteca Scrapy

## Critérios de aceitação

- [x] Código do Raspador
- [x] Arquivo.md

**Comment by LuizGust4vo** [comment]
O diretório do raspador criado, bem como os arquivos contendo os dados exportados, podem ser encontrados em: [Raspagem 'Quotes to Scrape'](https://github.com/unb-mds/2023-2-Squad09-Gotinha/tree/main/Prot%C3%B3tipos/Raspagem%20'Quotes%20to%20Scrape').

**Comment by LuizGust4vo** [comment]
Para complementar a Issue sobre Scrapy da sprint anterior, e comentar o raspador criado, segue o seguinte [Arquivo](https://github.com/unb-mds/2023-2-Squad09/blob/main/docs/Documenta%C3%A7%C3%A3o%20dos%20Prot%C3%B3tipos/Raspagem_'Quotes_to_Scrape'.md).
