### ISSUE TITLE
Extrair Diário Oficial usando o Scrapy

### ISSUE THREAD

**Issue by joao-artl** [unb-mds/2023-2-Squad09#37]
# Extrair Diário Oficial usando o Scrapy

## Descrição do problema
Realizar em paralelo com a [issue do Selium](https://github.com/unb-mds/2023-2-Squad09/issues/36) a extração do arquivo do Diário Oficial de Goiânia.

## Como o problema pode ser resolvido
Através da biblioteca Scrapy e da url obtida pelo Selenium correspondente ao Diário Oficial, conseguir extrair e armazenar o arquivo dos Diários Oficiais para eventual manipulação.

O Querido Diário possui uma [playlist](https://www.youtube.com/watch?v=3SCQl4cYB5I&list=PLpWp6ibmzPTc2rod9Hc822_3zMaq9G-qE) que pode auxiliar

## Critérios de aceitação

- [x] Código extrator com Scrapy
- [x] Arquivo Extraído

**Comment by LuizGust4vo** [comment]
[Código extrator](https://github.com/unb-mds/2023-2-Squad09-Gotinha/blob/main/Prot%C3%B3tipos/go_goiania/go_goiania_spider.py) para o município de Goiânia-GO.

**Comment by LuizGust4vo** [comment]
[Arquivo .json](https://github.com/unb-mds/2023-2-Squad09-Gotinha/blob/main/Prot%C3%B3tipos/go_goiania/goiania.json) e [Arquivo .csv](https://github.com/unb-mds/2023-2-Squad09-Gotinha/blob/main/Prot%C3%B3tipos/go_goiania/goiania.csv) extraídos.
