### ISSUE TITLE
Contato com OpenKnowledge

### ISSUE THREAD

**Issue by joao-artl** [unb-mds/2023-2-Squad09#4]
# Contato com OpenKnowledge

## Descrição do problema
Contato com os membros da OpenKnowledge para melhor entendimento do projeto Querido diário

## Como o problema pode ser resolvido
Neste contato estamos buscando saber: qual o tipo de tecnologia utilizada, quais cidades ainda não foram mapeadas e como podemos contribuir para o projeto

## Critérios de aceitação

- [x] Arquivo com detalhes do que foi discutido (.md)

**Comment by paulomh** [comment]
Pesquisa feita do projeto Querido Diário [link](https://github.com/unb-mds/2023-2-Squad09-Gotinha/blob/main/docs/Estudos/pesquisaOpenKnowledge.md)
