### ISSUE TITLE
Transformar PDFs do Diário Oficial em TXT

### ISSUE THREAD

**Issue by joao-artl** [unb-mds/2023-2-Squad09#40]
# Transformar PDFs do Diário Oficial em TXT

## Descrição do problema
O formato TXT é bastante usado no Querido Diário por ser mais flexivel e fácil de manipular. Considerando isso é importante converter os arquivos disponibilizados em PDF para este formato.

## Como o problema pode ser resolvido
O Apache Tika , o PyPDF2 e PyMuPDF são ferramentas capazes de realizar a conversão.
- [x] Avaliar qual a melhor ferramenta para conversão
- [x] Unir algoritmo conversor a [extrator](https://github.com/unb-mds/2023-2-Squad09/issues/37)

## Critérios de aceitação

- [x] Algoritmo conversor
- [x] Documentar processo de conversão

**Comment by yanzin00** [comment]
Código em Python que converge de .pdf para .txt [pdf_txt](https://github.com/unb-mds/2023-2-Squad09/blob/main/Protótipos/pdf_txt.py)

**Comment by yanzin00** [comment]
Código em Python [Pdf_txt](https://github.com/unb-mds/2023-2-Squad09-Gotinha/tree/main/Prot%C3%B3tipos/Conversor_PDF_json)

**Comment by yanzin00** [comment]
Documentação sobre avaliação da melhor ferramenta, uso do PyPDF2, Código: [Doc](https://github.com/unb-mds/2023-2-Squad09-Gotinha/blob/main/docs/Documenta%C3%A7%C3%A3o%20dos%20Prot%C3%B3tipos/pdf-json.md)
