### ISSUE TITLE
Integrar Protótipos em um único arquivo

### ISSUE THREAD

**Issue by joao-artl** [unb-mds/2023-2-Squad09#46]
# Integrar Protótipos em um único arquivo

## Como o problema pode ser resolvido
Unir protótipos de extrator, conversor de PDF para TXT e filtro, em um único arquivo 

## Critérios de aceitação

- [x] Código organizado

**Comment by yanzin00** [comment]
Código com o agrupamento dos códigos, responsável por extrair trechos de diversos diários oficiais e alocar em um arquivo novo [decretoOrçamentário.py](https://github.com/unb-mds/2023-2-Squad09/blob/main/Protótipos/Extrator/decretoOrçamentário.py)

**Comment by yanzin00** [comment]
Documentação [Link](https://github.com/unb-mds/2023-2-Squad09-Gotinha/blob/main/docs/Documentação%20dos%20Protótipos/orçamentário.md)
