### ISSUE TITLE
Mapeamento de tecnologias

### ISSUE THREAD

**Issue by joao-artl** [unb-mds/2023-2-Squad09#5]
# Mapeamento de tecnologias

## Descrição do problema
Para poder decidir qual a melhor tecnologia para o projeto é necessário também saber quais tecnologias os membros estão acostumados

## Como o problema pode ser resolvido
O excel permite criar mapas de calor para avaliar a melhor alternativa, porém outros aplicativos possuem funções parecidas

## Critérios de aceitação

- [x] Documento contendo o mapa das dificuldades

**Comment by yanzin00** [comment]
Documento contendo os gráficos, facilidades e dificuldades do grupo sobre as tecnologias: [Link ](https://github.com/unb-mds/2023-2-Squad09-Gotinha/blob/main/docs/Estudos/Mapeamento_de_tecnologias.md)
