### ISSUE TITLE
Finalizar tratamento dos dados dos diários oficiais

### ISSUE THREAD

**Issue by joao-artl** [unb-mds/2023-2-Squad09#59]
# Finalizar tratamento dos dados dos diários oficiais

## Descrição do problema
Um ideia proposta pela OpenKnowledge foi a utilização da API do Querido Diário como extrator, a API por sua vez torna mais pratico a busca pelos diários oficias, porém ela não possui todos os diários oficiais dos estados do Goias.
Considerando essas informações é importante buscar novas outras de extrair e tratar os dados dos diários oficiais

## Critérios de aceitação

- [x] Implementar outras ferramentas para tratamento dos dados ( elasticSearch, spacy, etc)
- [x] Documentar funcionamento

**Comment by yanzin00** [comment]
não conseguimos utilizar a API do Querido Diário, e a tentativa de implementar outra ferramenta está em andamento. No mais eu e o Luiz fizemos a junção dos códigos que extrai, converte e filtra os Diários oficiais. [Link](https://github.com/unb-mds/2023-2-Squad09-Gotinha/blob/main/docs/Documentação%20dos%20Protótipos/run.md) da Documentação.
