### ISSUE TITLE
Estudar sobre o React

### ISSUE THREAD

**Issue by joao-artl** [unb-mds/2023-2-Squad09#60]
# Estudar sobre o React

## Descrição do problema
O React é uma  das principais tecnologias utilizada no desenvolvimento do projeto, considerando isso é importante que ela se torne conhecida entre todos os membros. 

## Como o problema pode ser resolvido
Estudar sobre o React através da documentação, vídeos e tutoriais, e realizar um treinamento para a equipe sobre essa tecnologia.

## Critérios de aceitação

- [x] Documentar Estudo
- [x] Apresentação para a Equipe

**Comment by paulomh** [comment]
- Adicionada documentação sobre o estudo: [link](https://github.com/unb-mds/2023-2-Squad09-Gotinha/blob/main/docs/Estudos/React.md)

- Treinamento realizado por Paulo Henrique e Maria Eduarda na reunião do dia 08/11
