### ISSUE TITLE
Corrigir erro do GitHub Pages

### ISSUE THREAD

**Issue by joao-artl** [unb-mds/2023-2-Squad09#67]
# Corrigir erro do GitHub Pages

## Descrição do problema
Atualmente o GitHub Pages está com um problema que acaba por não carregar a página. Resolver este erro é importante para continuar o desenvolvimento do projeto.

## Critérios de aceitação

- [x] Link para o GitHub Pages corrigido

**Comment by paulomh** [comment]
Erro corrigido e página no ar através do link: [Gotinha](https://unb-mds.github.io/2023.2_Gotinha)
