### ISSUE TITLE
Viabilizar uso do Spacy

### ISSUE THREAD

**Issue by joao-artl** [unb-mds/2023-2-Squad09#68]
# Viabilizar uso do Spacy

## Descrição do problema
O Spacy é uma biblioteca capaz de filtrar os dados obtidos pelos extratores. É importante viabilizar a biblioteca a fim de garantir que seu uso será necessário no desenvolvimento do projeto.

## Como o problema pode ser resolvido
Executar testes que mostrem o funcionamento da biblioteca

## Critérios de aceitação

- [x] Algoritmo capaz de filtrar dados
- [x] Documentar processo

**Comment by yanzin00** [comment]
algoritmo capaz de filtrar os dados de vários queridos diários [spaCy](https://github.com/unb-mds/2023-2-Squad09-Gotinha/blob/main/Protótipos/Protótipo_Spacy/spaCy.ipynb) ( o código já esta comentado e de fácil compreensão )
