### ISSUE TITLE
Melhorar o readme do segundo repositório

### ISSUE THREAD

**Issue by joao-artl** [unb-mds/2023-2-Squad09#69]
# Melhorar o readme do segundo repositório

## Descrição do problema
Elaborar um readme com todas as informações relacionadas a instalação e utilização do projeto

## Critérios de aceitação

- [x] Link para o readme

**Comment by paulomh** [comment]
Readme do segundo repositório melhorado. Agora ele possui um tutorial completo para rodar o front-end localmente. Segue o link de acesso ao segundo repositório: [front-end-gotinha](https://github.com/unb-mds/2023.2_Gotinha)
