### ISSUE TITLE
Montar uma lista com os dados e disponibiliza-los na tela

### ISSUE THREAD

**Issue by joao-artl** [unb-mds/2023-2-Squad09#70]
# Montar uma lista com os dados e disponibiliza-los na tela

## Descrição do problema
Criar uma lista com os resultados da filtragem (baixa precisão) e inseri-los na dashboard do Gotinha

## Critérios de aceitação

- [x] Extrator funcional na dashboard
- [x] Dados iniciais disponibilizados na tela

**Comment by yanzin00** [comment]
[extrator](https://github.com/unb-mds/2023-2-Squad09-Gotinha/tree/main/Protótipos/Extrator_V2)
