### ISSUE TITLE
Plotar gráficos feitos com o ApexCharts

### ISSUE THREAD

**Issue by joao-artl** [unb-mds/2023-2-Squad09#71]
# Plotar gráficos feitos com o ApexCharts

## Descrição do problema
Utilizar a biblioteca ApexCharts para plotar os gráficos responsáveis pelo orçamento da saúde nos municípios do Goías

## Critérios de aceitação

- [x] Gráficos iniciais disponíveis na dashboard
- [x] Documentar processo

**Comment by paulomh** [comment]
- Gráficos desenhados e implementados na página, porém, sem dados: [pagina-projeto](https://unb-mds.github.io/2023.2_Gotinha)
- Documentação do processo: [documento](https://github.com/unb-mds/2023-2-Squad09-Gotinha/blob/main/docs/Documentação%20dos%20Protótipos/DocumentacaoGraficos.md)

**Comment by paulomh** [comment]
Todos os critérios foram deferidos
